### ISSUE TITLE
Does not work after update to 2.1.0

### ISSUE THREAD

**Issue by Bjoernsen** [pivotal/LicenseFinder#216]
I am not able to use `license_finder` after the release of `2.1.0`.
When I use version `2.0.4`, it works as expected.

I tried to delete `config/license_finder.yml` and `config/dependency_decisions.yml` without success.

The error
```ruby
/home/bjoernsen/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xa8fcc8 license_finder-2.1.0> (NoMethodError)
	from /home/bjoernsen/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /home/bjoernsen/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@test_gemset/gems/license_finder-2.1.0/bin/license_finder:3:in `<top (required)>'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@test_gemset/bin/license_finder:23:in `load'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@test_gemset/bin/license_finder:23:in `<main>'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@test_gemset/bin/ruby_executable_hooks:15:in `eval'
	from /home/bjoernsen/.rvm/gems/ruby-2.3.0@test_gemset/bin/ruby_executable_hooks:15:in `<main>'
```

System
- Ubuntu 14.04 LTS
- ruby: 2.3.0
- rails: 4.2.6
- rvm: 1.26.11

**Comment by flavorjones** [comment]
Hi @Bjoernsen,

Thanks for opening this issue up. Is there anything else you can tell me about your project to help me reproduce this? Would you be able to share your Gemfile (or other package management files) with me?

All our tests are [green](https://travis-ci.org/pivotal/LicenseFinder), so I'd like to figure out what you're doing differently from what we're testing.

**Comment by Bjoernsen** [comment]
I think I found the reason.

I copied my Gemfile to a new folder and created a new gemset (rvm). After `gem install bundler && bundle install` and `gem install license_finder`, I tried `license_finder report > /dev/null`. It worked.

Back in my original project folder `license_finder` worked in combination with the new gemset, but not with the original one. I recognized that the `license_finder` had installed some dependencies. One of them had been `rubyzip`.

In my new test gemset, only version `1.2.0` was available, but in the project gemset, version `1.2.0` and `1.1.7` were present. I uninstalled `1.1.7`.

Now it works.

**Comment by flavorjones** [comment]
Great! Thank you for following up. I'm going to close this issue.

**Comment by mikecmpbll** [comment]
having the same problem but the project i'm trying to run this against depends on rubyzip 0.7.7 . i'm not sure why this is happening though as I have a more recent version installed also.

does licensefinder load the project dependencies or the bundle env at some point?

**Comment by mikecmpbll** [comment]
```
irb -rlicense_finder
2.3.1 :001 > LicenseFinder::CLI::Main.start
```

as a workaround
